databaseChangeLog:
  - changeSet:
      id: insert-values-to-users-roles
      author: andriy_hrynevetskyi
      changes:
        - insert:
            tableName: users_roles
            columns:
              - column: {name: user_id, value: 1}
              - column: {name: role_id, value: 1}
        - insert:
            tableName: users_roles
            columns:
              - column: {name: user_id, value: 2}
              - column: {name: role_id, value: 2}